### ISSUE TITLE
Loadbalancer External IP Wrong When Set Up With hostname-only-ingress

### ISSUE THREAD

**Issue by ErjanGavalji** [linode/linode-cloud-controller-manager#358]
Hi,

When creating a LoadBalancer service with the annotation suffix of `hostname-only-ingress` (as per [the article](https://techdocs.akamai.com/cloud-computing/docs/get-started-with-load-balancing-on-an-lke-cluster)), printing the details of the k8s LoadBalancer service brings the Linode NodeBalancer host name instead of its external IP address.

We found out that when we use the `hostname-only-ingress` annotation our internal requests to the domain name the nodebalancer (and the ingress) is associated with start working properly, which is a desired effect. However, the `kubectl get service` command does not print the IP address in the External IP field.

Please, check [a quick and easy repro I created](https://github.com/ErjanGavalji/linode-nodebalancer-id-bug/tree/external-ip-wrong)

Cheers,
Erjan Gavalji

**Comment by rahulait** [comment]
This is as expected. K8s looks at the status of service to fill external ip field. We don't set ip when using `hostname-only-ingress` and hence it uses hostname instead of ip.

Service status without annotation:
```
status:
  loadBalancer:
    ingress:
    - hostname: 172-232-177-101.ip.linodeusercontent.com
      ip: 172.232.177.101
      ipMode: VIP
```

Status with annotation `service.beta.kubernetes.io/linode-loadbalancer-hostname-only-ingress: "true"`
```
status:
  loadBalancer:
    ingress:
    - hostname: 172-232-178-142.ip.linodeusercontent.com
```

Based on documentation: 
```
When true, the LoadBalancerStatus for the service will only contain the Hostname. 
This is useful for bypassing kube-proxy's rerouting of in-cluster requests originally 
intended for the external LoadBalancer to the service's constituent Pod IP addresses.
```
